[package]
name = "minidisc-cli"
homepage = "https://github.com/G2-Games/minidisc-rs"
repository = "https://github.com/G2-Games/minidisc-rs"
readme = "README.md"
version = "0.0.1"
edition = "2021"
authors = ["G2 <g2@g2games.dev>"]
license = "AGPL-3.0"

[dependencies]
futures = "0.3.30"
hex = "0.4.3"
nusb = "0.1.4"
tokio = { version = "1.35.1", features = ["full"] }
translit = "0.5.0"

[dependencies.minidisc-rs]
path = "minidisc-rs"
version = "0.0.1"
