[package]
name = "minidisc-rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nofmt = "1.0.0"
once_cell = "1.18.0"
rusb = "0.9.3"

