[package]
name = "minidisc-cli"
homepage = "https://github.com/G2-Games/minidisc-rs"
repository = "https://github.com/G2-Games/minidisc-rs"
readme = "README.md"
version = "0.0.1"
edition = "2021"
authors = ["G2 <g2@g2games.dev>"]
license = "AGPL-3.0"

[dependencies]
rusb = "0.9.3"

[dependencies.minidisc]
path = "minidisc-rs"
version = "0.0.1"
