[package]
name = "minidisc-cli"
homepage = "https://github.com/G2-Games/minidisc-rs"
repository = "https://github.com/G2-Games/minidisc-rs"
readme = "README.md"
version = "0.0.1"
edition = "2021"
authors = ["G2 <g2@g2games.dev>"]
license = "AGPL-3.0"

[dependencies]
hex = "0.4.3"
cross_usb = { path = "/home/g2/Documents/projects/code/rust/cross-usb/" }
[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1.35.1", features = ["full"] }

[dependencies.minidisc_rs]
path = "minidisc-rs"
version = "0.0.1"
